name: Nomogram Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt

    - name: Install Xvfb
      run: sudo apt-get update && sudo apt-get install -y xvfb

    - name : make pynguin tests
      run : pip install pynguin
            export PYNGUIN_DANGER_AWARE=3
            mkdir /tmp/pynguin-results
            pynguin \
            --project-path ./src/app \
            --output-path /tmp/pynguin-results \
            --module-name main
    
